version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: fs-extra
    versions:
    - 9.0.1
    - 9.1.0
  - dependency-name: tslint
    versions:
    - 6.1.3
  - dependency-name: "@commitlint/prompt-cli"
    versions:
    - 11.0.0
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: flatted
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.6
  - dependency-name: standard-version
    versions:
    - 8.0.1
  - dependency-name: "@types/hapi__joi"
    versions:
    - 17.1.6
  - dependency-name: "@hapi/joi"
    versions:
    - 17.1.1
